version: '3.8'

services:
  site-lab:
    # On change le nom du service
    build: .
    container_name: site-lab # IMPORTANT : Nom unique pour Ã©viter le conflit
    restart: always
    networks:
      - tunnel_network

networks:
  tunnel_network:
    external: true
